const API_BASE_PATH = window.API_BASE_PATH

const api = {
    CART_ITEMS                       : `${API_BASE_PATH}/cart/items`,
    CHECKOUT                         : `${API_BASE_PATH}/transactions/checkout`,
    CLEAR_OTP_FORGOT_PASSWORD        : `${API_BASE_PATH}/public/forgotPassword/clearOtp`,
    CONDIMENTS                       : `${API_BASE_PATH}/condiments`,
    CONDIMENTS_INGREDIENTS           : `${API_BASE_PATH}/condiments/ingredients`,
    CONDIMENT_BY_OPTIONID            : `${API_BASE_PATH}/condiments/findByOptionId`,
    COUPONS                          : `${API_BASE_PATH}/coupons`,
    COUPONS_SEARCH                   : `${API_BASE_PATH}/coupons/search`,
    INVOICES                         : `${API_BASE_PATH}/invoices`,
    INVOICES_SEARCH                  : `${API_BASE_PATH}/invoices/search`,
    LOCATIONS_BOUNDARY               : `${API_BASE_PATH}/vendingMachine/findByBoundary`,
    LOCATIONS_NEAREST                : `${API_BASE_PATH}/locations/nearest`,
    LOGIN                            : `${API_BASE_PATH}/public/login`,
    LOGIN_OTP_EMAIL                  : `${API_BASE_PATH}/public/login/sendOtp`,
    LOGIN_SECURITY_VERIFICATION      : `${API_BASE_PATH}/public/login/verify`,
    LOGIN_SECURITY_VERIFICATION_CLEAR: `${API_BASE_PATH}/public/login/clearOtp`,
    OTP_FORGOT_PASSWORD              : `${API_BASE_PATH}/public/forgotPassword/createOtp`,
    ORDERS                           : `${API_BASE_PATH}/orders`,
    ORDERS_SEARCH                    : `${API_BASE_PATH}/orders/search`,
    PRODUCTS                         : `${API_BASE_PATH}/products`,
    PRODUCTS_MAIN_INGREDIENTS        : `${API_BASE_PATH}/products/ingredients/main`,
    PRODUCT_ORDERS                   : `${API_BASE_PATH}/productOrders`,
    GET_NUTRITIONFACTS               : `${API_BASE_PATH}/condiments/condimentnf`,
    FIND_PRODUCT_ORDER_BY_IDS        : `${API_BASE_PATH}/productOrder/findByProductAndOrderID?`,
    GET_ORDER_QUANTITY               : `${API_BASE_PATH}/productOrders/search/findCartQuantity?`,
    ADD_ORDERS                       : `${API_BASE_PATH}/productOrder/addOrder`,
    CLEAR_CART                       : `${API_BASE_PATH}/productOrder/deleteOrder`,
    PRODUCT_CONDIMENT_ORDERS         : `${API_BASE_PATH}/productOptionOrder`,
    RECEIPT                          : `${API_BASE_PATH}/transactions/receipt`,
    TRANSACTIONS_SEARCH              : `${API_BASE_PATH}/transactions/findByOrderId`,
    TRANSACTION_HISTORY              : `${API_BASE_PATH}/transactions/history`,
    REGISTER                         : `${API_BASE_PATH}/public/register`,
    REGISTER_APPLE_ACCOUNT           : `${API_BASE_PATH}/public/register/verify/appleAccount`,
    REGISTER_GOOGLE_ACCOUNT          : `${API_BASE_PATH}/public/register/verify/googleAccount`,
    REGISTER_VERIFY                  : `${API_BASE_PATH}/public/register/verify`,
    UNSUBSCRIBE_EMAIL                : `${API_BASE_PATH}/public/unsubscribe`,
    REGISTER_VERIFY_GUEST            : `${API_BASE_PATH}/public/register/verify/guest`,
    USER_UPDATE                      : `${API_BASE_PATH}/users/update`,
    USER_UPDATE_VERIFICATION         : `${API_BASE_PATH}/public/users/update/verify`,
    USER_SEARCH                      : `${API_BASE_PATH}/users/search`,
    USERS                            : `${API_BASE_PATH}/users`,
    USERS_BY_EMAIL                   : `${API_BASE_PATH}/public/search/findByEmail`,
    USERS_BY_PHONE_NUMBER            : `${API_BASE_PATH}/public/search/findByPhoneNumber`,
    USERS_BY_TOKEN                   : `${API_BASE_PATH}/public/search/findByToken`,
    USERS_FORGOT_PASSWORD            : `${API_BASE_PATH}/public/forgotPassword`,
    USERS_NEW_PASSWORD               : `${API_BASE_PATH}/public/newPassword`,
    USERS_VERIFICATION_CODE          : `${API_BASE_PATH}/public/verification`,
    USERS_FP_VERIFICATION_CODE       : `${API_BASE_PATH}/public/verification/forgotpassword`
}

export default api