api:
  internal: ${API_INTERNAL}
cors:
  allowedOrigins: ${ALLOWED_ORIGINS}
spring:
  application:
    name: CORE-SERVICE
  data:
    rest:
      base-path: api
  datasource:
    password: ${ROBOBURGER_DB_PASSWORD}
    url: ${ROBOBURGER_DB_URL}
    username: ${ROBOBURGER_DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2019Dialect
        format_sql: true
    show-sql: false